/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_byd_myapplication_jniutil_JniUtils */

#ifndef _Included_com_byd_myapplication_jniutil_JniUtils
#define _Included_com_byd_myapplication_jniutil_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_byd_myapplication_jniutil_JniUtils
 * Method:    getGewei
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_byd_myapplication_jniutil_JniUtils_getGewei
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
